### ISSUE TITLE
hol-mode: company-yasnippet shadows other company backends

### ISSUE THREAD

**Issue by ycpei** [HOL-Theorem-Prover/HOL#1003]
Not sure why the following is in hol-mode.src,

```elisp
(when (locate-library "company-yasnippet")
  (load-library "company")
  (setq company-backends (cons 'company-yasnippet company-backends)))
```

The code seems totally unrelated to hol.

And it shadows other backends[1], so when yas-global-mode is on, one can no longer get code completion in say emacs-lisp mode.

Perhaps remove this snippet?

[1]: See company-yasnippet.el:

```elisp
(defun company-yasnippet (command &optional arg &rest ignore)
  "`company-mode' backend for `yasnippet'.

This backend should be used with care, because as long as there are
snippets defined for the current major mode, this backend will always
shadow backends that come after it.
```

**Comment by mn200** [comment]
This sounds plausible.  I don't use that code myself, so haven't encountered any issues with it.  Is there a "right" way to do this?

**Comment by ycpei** [comment]
I think the right way is to simply remove the code - what do people think?

**Comment by mn200** [comment]
The code dates back to https://github.com/HOL-Theorem-Prover/HOL/pull/476 ; it was adding value for @HeikoBecker I assume, so I wonder if he has an opinion...

**Comment by HeikoBecker** [comment]
The `company-mode` integration was added by me back then because it gives the whole thing a more IDE-like feeling. The code before this configuration sets up `yasnippet` to use snippets that I added to HOL4. It was meant to make working with definitions and theorems easier, as one had to write some things twice back in the day when there were no `Definition` and `Theorem` keywords.
I agree that it should not shadow other company backends though.  I have submitted it as a PR to fix it: #1004

**Comment by ycpei** [comment]
@HeikoBecker Thanks, I'm not sure I understand how that PR fixes the shadowing - it does not touch hol-mode.src, so with this PR the code snippet would still run and add company-yasnippet to the front of the company-backends list, no?

**Comment by HeikoBecker** [comment]
Thanks for notificing. I accidentally edited the wrong file. The PR includes the correct file (`hol-mode.src`) now.

**Comment by mn200** [comment]
I think this is now closed.
