### ISSUE TITLE
floating-point, float_is_sign_minus

### ISSUE THREAD

**Issue by michael-roe** [HOL-Theorem-Prover/HOL#1054]
I'd like to add float_is_sign_minus from the IEEE 754 standard, something along the lines of:

val float_is_sign_minus_def = Define`
    float_is_sign_minus (x: ('t, 'w) float) =
       (x.Sign = 1w)`

On its own, that doesn't seem to work, because evaluation with EVAL ``float_is_sign_minus(^f1)``  doesn't seem to work.  I don't understand HOL4 well enough to know what else is needed here.

**Comment by mn200** [comment]
I assume you're editing `binary_ieeeScript.sml`.  The reason is that `Define` there is rebound at the head of the file to `zDefine` which means all definitions are explicitly `noncompute` (meaning that `EVAL` won't use them).  This makes sense if you're going to handle evaluation with custom code that can do smart things with rounding.  You could rework all of the definitions there with the 
```
Definition foo_def[nocompute]:
  ...
End
```
syntax, but it might be easier to explicitly make your definition `compute` by writing:
```
Definition float_is_sign_minus_def[compute]:
  float_is_sign_minus x <=> x.Sign = 1w
End
```

Incidentally, this is such a trivial definition that I would be tempted to just make it an overload:
```
Overload float_is_sign_minus = “\x. x.Sign = 1w”
```
then you don't need to worry about evaluation and simplification because the notation is purely at the level of HOL printing and parsing.
