### ISSUE TITLE
Feature request: cleanup use abstractions

### ISSUE THREAD

**Issue by ordinarymath** [HOL-Theorem-Prover/HOL#1332]
Hi I noticed that there are extremely weird abstraction for use that mainly served as a way to save typing.
one particularly bad example is https://github.com/HOL-Theorem-Prover/HOL/blob/develop/tools/Holmake/hmcore.ML and stuff like 
`
val origdir = OS.FileSys.getDir();
OS.FileSys.chDir "../../../tools-poly";
val _ = use "poly/poly-init.ML";
OS.FileSys.chDir origdir;
`
another pattern is useC which has two different definitions in poly-build.ML and poly-Holmake.ML
where it will import based on some relative path instead of the current dir.
could this be cleaned up?

**Comment by mn200** [comment]
Saving typing is a valuable way to eliminate "code smell".  `hmcore.ML` is used only in compiling/assembling (some of) the source files that implement `Holmake`, doesn't expose its bindings to future clients, and is short and sweet.  The same is true of the other scripts you identify.

The need to change directory to get certain source files to work (because they themselves assume they are being executed in certain directories) is indeed rather gross, but I'm loath to change working code.  (We would have to use absolute paths everywhere, which would in turn require us to make sure all that code had access to the `HOLDIR` value or similar.)
