### ISSUE TITLE
LEX needs mono and cong theorems

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#219]
Inductive relations and recursive functions that recurse through `LEX` fail or get unprovable termination conditions. The following theorems need to be included somewhere (probably `pairTheory`). There may be issues since `pairTheory` is so early in the build sequence.
```
val LEX_CONG = store_thm("LEX_CONG",
  ``(R1 x1 x2 <=> R1' x1' x2') /\
    (~(R1 x1 x2) ==> ((x1 = x2) <=> (x1' = x2'))) /\
    (~(R1 x1 x2) ==> (R2 y1 y2 <=> R2' y1' y2'))
    ==> ((R1 LEX R2) (x1,y1) (x2,y2) <=> (R1' LEX R2') (x1',y1') (x2',y2'))``,
  SRW_TAC[][LEX_DEF_THM] THEN METIS_TAC[])
val () = DefnBase.export_cong"LEX_CONG"

val LEX_MONO = store_thm("LEX_MONO",
  ``(!x y. R1 x y ==> R2 x y) /\
    (!x y. R3 x y ==> R4 x y)
    ==>
    (R1 LEX R3) x y ==> (R2 LEX R4) x y``,
  STRIP_TAC THEN
  Cases_on`x` THEN Cases_on`y` THEN
  SRW_TAC[][LEX_DEF_THM] THEN
  PROVE_TAC[])
val () = IndDefLib.export_mono"LEX_MONO"
```

**Comment by xrchz** [comment]
@konrad-slind: Has there been progress on that bug you were fixing?

**Comment by konrad-slind** [comment]
I'm not sure. I remember getting to the bottom of one bug, and installing
the fix. Have you got a small example showing the problem?

Thanks,
Konrad.

**Comment by xrchz** [comment]
Actually, I don't think there is a problem I have. This issue was about wanting those three theorems to be included under `src` somewhere. And wondering if there is a suitable congruence rule for `LLEX`.

**Comment by konrad-slind** [comment]
Hi Ramana,

  I looked up my fix. It supports the following comparison function on
first order terms, which is analogous to the problem that Scott had. I had
to fix the code, and also the congruence rule for "pair_cmp" needs to have
a particular syntax in setting up for the recursive rewriting in the
termination
condition extractor. In this congruence rule, the twist is that both pairs
need to
be unpacked in order to get the subcomponents being recursed upon

> comparisonTheory.pair_cmp_cong;
val it =
   |- ∀cmp1 cmp2 v1 v2 cmp1' cmp2' v1' v2'.
     (v1 = v1') ∧ (v2 = v2') ∧
     (∀a b c d.
        (v1' = (a,b)) ∧ (v2' = (c,d)) ⇒ (cmp1 a c = cmp1' a c)) ∧
     (∀a b c d.
        (v1' = (a,b)) ∧ (v2' = (c,d)) ⇒ (cmp2 b d = cmp2' b d)) ⇒
     (pair_cmp cmp1 cmp2 v1 v2 = pair_cmp cmp1' cmp2' v1' v2'):
   thm

Maybe this will help in formulating the right congruence for LLEX.

Konrad.

***************************************************************************

load "stringLib";

(* May have to first invoke Holmake in
   HOLDIR/examples/balanced_bst
*)

load (HOLDIR^"/examples/balanced_bst/balanced_mapTheory");
open comparisonTheory; (* source in HOLDIR/src/enumfset *)

(*---------------------------------------------------------------------------*)
(* Datatype of first-order terms.
 *)
(*---------------------------------------------------------------------------*)

val _ = Hol_datatype
  `term
     = Var of string
     | App of string => term list`;

val term_size_def = fetch "-" "term_size_def";
val term_induction = fetch "-" "term_induction";

(*---------------------------------------------------------------------------*)
(* Comparison function on terms.
  *)
(*---------------------------------------------------------------------------*)

val term_cmp_def =
 tDefine
 "term_cmp"
 `(term_cmp (Var x1) (Var x2) = string_cmp x1 x2) ∧
  (term_cmp (Var _) (App _ _) = Less) ∧
  (term_cmp (App _ _) (Var _) = Greater) ∧
  (term_cmp (App x1 ts1) (App x2 ts2) =
     pair_cmp string_cmp (list_cmp term_cmp) (x1,ts1) (x2,ts2))
 `
 (RW_TAC list_ss [] THEN
  WF_REL_TAC `measure (term_size o FST)` THEN
  Induct_on `ts1` THEN RW_TAC list_ss [term_size_def] THENL
  [ALL_TAC, RES_TAC THEN POP_ASSUM (MP_TAC o SPEC_ALL)] THEN DECIDE_TAC);

**Comment by konrad-slind** [comment]
I think the congruence rule for LEX should be quite similar to that
for pair_cmp_cong, adding in extra info for ~(R1 a c = R1' a c) in the
second part. So something like

  !R1 R2 v1 v2 R1' R2' v1' v2'.
     (v1 = v1') /\ (v2 = v2') /\
     (!a b c d. (v1' = (a,b)) /\ (v2' = (c,d)) ==> (R1 a c = R1' a c)) /\
     (!a b c d. (v1' = (a,b)) /\ (v2' = (c,d)) /\ ~(R1 a c = R1' a c) ==>
(R2 b d = R2' b d))
   ==>
    ($LEX R1 R2 v1 v2 = $LEX R1' R2' v1' v2')

is needed. It should be provable in pairScript.sml I would think.

Konrad.

**Comment by konrad-slind** [comment]
Here's what I have for LEX_CONG (what I wrote above is wrong).

open pairTheory;
val LEX_CONG = Q.store_thm
("LEX_CONG",
 `!R1 R2 v1 v2 R1' R2' v1' v2'.
     (v1 = v1') /\ (v2 = v2') /\
     (!a b c d. (v1' = (a,b)) /\ (v2' = (c,d)) ==> (R1 a c = R1' a c)) /\
     (!a b c d. (v1' = (a,b)) /\ (v2' = (c,d)) /\ (a=c) ==> (R2 b d = R2' b
d))
   ==>
    ($LEX R1 R2 v1 v2 = $LEX R1' R2' v1' v2')`,
 SIMP_TAC std_ss [LEX_DEF,FORALL_PROD] THEN METIS_TAC[]);

LLEX needs more thought. And examples would be nice.

Konrad.

**Comment by xrchz** [comment]
Regarding examples, my use of `LLEX` is here: https://github.com/CakeML/cakeml/blob/master/hol-light/standard/syntax/holSyntaxScript.sml#L131

**Comment by konrad-slind** [comment]
OK good. I modified the relation to be a recursive function (just an
example for testing).
Turns out that comparisonTheory.list_cmp_cong is a good template to use for
stating LLEX_CONG. Really, I am not sure that LLEX is useful, but if
you think it is, please do add LLEX_CONG to the system.

Cheers,
Konrad.

********************************************************************************

load "stringLib";

open pairTheory comparisonTheory; (* source in HOLDIR/src/enumfset *)

(*---------------------------------------------------------------------------*)
(* Datatype of first-order terms.
 *)
(*---------------------------------------------------------------------------*)

val _ = Hol_datatype
  `term
     = Var of string
     | App of string => term list`;

val term_size_def = fetch "-" "term_size_def";

val LEX_CONG = Q.store_thm
("LEX_CONG",
 `!R1 R2 v1 v2 R1' R2' v1' v2'.
     (v1 = v1') /\ (v2 = v2') /\
     (!a b c d. (v1' = (a,b)) /\ (v2' = (c,d)) ==> (R1 a c = R1' a c)) /\
     (!a b c d. (v1' = (a,b)) /\ (v2' = (c,d)) /\ (a=c) ==> (R2 b d = R2' b
d))
   ==>
    ($LEX R1 R2 v1 v2 = $LEX R1' R2' v1' v2')`,
 SIMP_TAC std_ss [LEX_DEF,FORALL_PROD] THEN METIS_TAC[]);

val LLEX_CONG = Q.store_thm
("LLEX_CONG",
 `!R l1 l2 R' l1' l2'.
    (l1 = l1') /\ (l2 = l2') /\
    (!a b. MEM a l1' /\ MEM b l2' ==> (R a b = R' a b))
    ==>
    (LLEX R l1 l2 = LLEX R' l1' l2')`,
 GEN_TAC THEN Induct THENL [ALL_TAC, GEN_TAC] THEN Induct THEN RW_TAC
list_ss []
   THEN RW_TAC list_ss [listTheory.LLEX_THM]
   THEN FULL_SIMP_TAC list_ss []
   THEN METIS_TAC[]);

val _ = List.app DefnBase.add_cong [LEX_CONG,LLEX_CONG];

(*---------------------------------------------------------------------------*)
(* Example
  *)
(*---------------------------------------------------------------------------*)

val lt_string_def =
 Define
  `lt_string s1 s2 = (string_cmp s1 s2 = Less)`;

val lt_term_def = tDefine
 "lt_term"
 `(lt_term (Var s1) (Var s2) = lt_string s1 s2) /\
  (lt_term (Var _) (App _ _) = T) /\
  (lt_term (App _ _) (Var _) = F) /\
  (lt_term (App f flist) (App g glist) = (lt_string LEX (LLEX lt_term))
(f,flist) (g,glist))`
 (WF_REL_TAC `measure (term_size o FST)`
   THEN Induct_on `flist`
   THEN RW_TAC list_ss [term_size_def]
   THENL
     [ALL_TAC, RES_TAC THEN POP_ASSUM (MP_TAC o SPEC_ALL)]
   THEN DECIDE_TAC);
