### ISSUE TITLE
compiler bug for certain record component names

### ISSUE THREAD

**Issue by rauhbein** [HOL-Theorem-Prover/HOL#224]
HOL compilation does not work correctly for certain names of record components. That is, if you build a script with the line

`val () = Datatype `bar = <| size : num |>``

then a theory file is created without error. However, this theory will fail to load.You also get a similar problem with

```
val () = Datatype `A_x = <| y : num |>`
val () = Datatype `A = <| x : A_x |>`
```
##

**Comment by mn200** [comment]
Thanks for the bug report!

**Comment by mn200** [comment]
The second scenario is now (as of 774e10f55) fixed.  The first can be worked around by using a different name than `size` in the definition, and then using `add_record_field` and `add_record_fupdate`.  For example:

    val _ = Datatype`foo = <| n : num ; sz : num ; b : bool |>`;
    val _ = add_record_field ("size", ``foo_sz``);
    val _ = add_record_fupdate ("size", ``foo_sz_fupd``);

The use of overloading behind these calls will make literals, updates and accessors all print with `size` rather than `sz`.  The latter will also be presented as `size`.  *E.g.:*

    > ``x with sz := 10``;
    val it = ``x with size := 10``: term

I hope to fix this issue entirely in the near future of course.
