### ISSUE TITLE
Holmake confused by equal sig/struct/file names

### ISSUE THREAD

**Issue by ptroja** [HOL-Theorem-Prover/HOL#232]
Holmake dependency resolving is confused when signature, structure and file names are equal.

For example, if I create an empty directory with two files, `Foo.sig`:
```
open HolKernel Parse boolLib

signature Foo =
sig

  val bar : tactic

end
```
and `Foo.sml`:
```
open HolKernel Parse boolLib

structure Foo :> Foo =
struct

  val bar = ALL_TAC

end
```
I get:
```
$ Holmake
Analysing Foo.sig
Trying to create directory .HOLMK for dependency files
Holmake: Foo.ui seems to depend on itself - failing to build it
```

I am not sure if it is because of bug or because of undocumented (yet required) naming convention.

**Comment by xrchz** [comment]
At a glance, your `Foo.{sig,sml}` looks to be following HOL4 conventions correctly. Have you tried `Holmake cleanDeps; Holmake`? I just tried creating those files and `Holmake` (and `Holmake Foo.uo`) worked fine.

**Comment by ptroja** [comment]
In my setup `Holmake cleanDeps` does not help (and `Holmake cleanAll` neither).

Here is a debug log:
```
$ Holmake cleanDeps; Holmake cleanAll

$ ls -la
total 120
drwxrwxr-x  2 ptroja ptroja   4096 Feb  9 13:24 .
drwxrwxrwt 31 root   root   106496 Feb  9 13:24 ..
-rw-rw-r--  1 ptroja ptroja     75 Feb  9 11:49 Foo.sig
-rw-r-----  1 ptroja ptroja     86 Feb  9 11:49 Foo.sml

$ Holmake --d
Holmake: CommandLine.name() = Holmake
Holmake: CommandLine.arguments() = --d
Holmake: running /home/ptroja/briswork/Tools/HOL/bin/Holmake
Holmake: Looking to see if I am in a HOL distribution.
Holmake: Not in a HOL distribution
HOLDIR = /home/ptroja/briswork/Tools/HOL
POLYMLLIBDIR = /opt/polyml.5.5.2/lib
Targets = []
Additional includes = []
Using HOL sigobj dir = true
Generated targets are: [Foo.ui(*), Foo.uo(*)]
Working on target: Foo.ui
 Working on target: Foo.sig
Analysing Foo.sig
Holdep: Foo.ui: Foo.ui /home/ptroja/briswork/Tools/HOL/sigobj/HolKernel.ui /home/ptroja/briswork/Tools/HOL/sigobj/Parse.ui /home/ptroja/briswork/Tools/HOL/sigobj/boolLib.ui 

Trying to create directory .HOLMK for dependency files
Secondary dependencies for Foo.ui are: [/home/ptroja/briswork/Tools/HOL/sigobj/Overlay.ui, Foo.ui, /home/ptroja/briswork/Tools/HOL/sigobj/HolKernel.ui, /home/ptroja/briswork/Tools/HOL/sigobj/Parse.ui, /home/ptroja/briswork/Tools/HOL/sigobj/boolLib.ui]
 Working on target: /home/ptroja/briswork/Tools/HOL/sigobj/Overlay.ui
 /home/ptroja/briswork/Tools/HOL/sigobj/Overlay.ui outside current directory; considered OK.
 Working on target: Foo.ui
Holmake: Foo.ui seems to depend on itself - failing to build
```

**Comment by mn200** [comment]
I believe the issue you are seeing is caused by the  `open` before the `structure` and `signature` declarations.

This means you are not in actually in the “standard subset”.  Nonetheless, I agree that the behaviour is wrong.  I assume you are not using the most recent possible working version.  As of 37d61e338, you should find that this no longer happens.  (I can run the new `holdeptool.exe` program on your `Foo.sig` and see that its dependencies are just those modules that are `open`-ed.)

All that said, I would still try to conform, and would remove the `open` line from the `sig` file entirely, and move it to be within the `structure` in the other file.  This convention is one that we picked up from Moscow ML.  It is perhaps a little restrictive, but it does keep the top-level namespace clean.

**Comment by mn200** [comment]
Your point about lack of documentation is well taken though.  I will adjust §6.3.3 in the Description manual so that it says more about this.

**Comment by ptroja** [comment]
Thank you both for your replies. The problem disappeared after refreshing my setup to the latest working version (5d59df252fb20a1ea6c8a06104b02c35f070b264).

I will keep this issue opened until the Description is updated. (I blindly followed the Description's advice and put `open` at the top, as it is suggested for theory files.)
