### ISSUE TITLE
hol-kananaskis-10 does not build on ARM architecture

### ISSUE THREAD

**Issue by cvatavu** [HOL-Theorem-Prover/HOL#253]
I have a Fedora Core 21 on an ARM armv7l with 1GB RAM but I am unable to build HOL.
I have tried with both polyml 5.5.2 and mosml (kfl-mosml-96407bc).
With polyml it stops at "Linking boolScript.uo to produce theory-builder executable" with error:

polyml "constant too distant (16-bit offset)"

However, with mosml:

Build failed in directory ...hol-kananaskis-10/src/relation

Can you give me some pointers for building on ARM?

thanks
##

**Comment by mn200** [comment]
I suspect 1GB of memory is too little for Poly/ML, but nonetheless, I'm sure that David Matthews (the principal Poly/ML developer) would be keen to hear about that error.  (It may just be a symptom of running out of memory.)

What output did you get before the Moscow ML error message?

**Comment by cvatavu** [comment]
Here is the error:

Holmake: ~/misc/src/hol-kananaskis-10/src/basicProof
Uploading files to /home/.../misc/src/hol-kananaskis-10/sigobj
Building directory src/relation [20 Apr, 12:52:25]
Holmake: ~/misc/src/hol-kananaskis-10/src/relation
Compiling relationScript.sml
File "relationScript.sml", line 899, characters 11-15:
!       val [R,P] = fst(strip_forall(concl wf_thm0))
!            ^^^^
! Warning: pattern matching is not exhaustive

Linking relationScript.uo to produce theory-builder executable
Uncaught exception:
HOL_ERR
Build failed in directory /home/.../misc/src/hol-kananaskis-10/src/relation
(END)

**Comment by mn200** [comment]
Can you run `hol.bare` after getting as far as the above?  If so, can you `load "tautLib";`?  Can you run the `minisat` executable that is installed in `src/HolSat/sat_solvers/minisat/`.  (I am wondering if your error is caused by attempting to run `minisat`, which happens before a theory even begins to execute its proofs thanks to its use in `tautLib`.)

If you have a `minisat` executable in that directory, what happens if you rename it away from that name and try rebuilding?

**Comment by mn200** [comment]
Can reopen if we learn more about this issue.
