### ISSUE TITLE
Weaker than expected reduction in computeLib

### ISSUE THREAD

**Issue by bacam** [HOL-Theorem-Prover/HOL#267]
When `computeLib.set_skip` is used to prevent the reduction of trailing arguments, the other arguments that _are_ reduced are only weakly reduced.  I find this is counterintuitive when dealing with records; for example in

```
> val () = Datatype `foo = <| bar : num |>`;
<<HOL message: Defined type: "foo">>
> computeLib.EVAL_CONV ``x with <| bar := case y : num option of NONE => 1+1 | SOME _ => 2+2 |>``;
val it =
   |- x with bar := case y of NONE => 1 + 1 | SOME v => 2 + 2 =
   x with bar := case y of NONE => 2 | SOME v => 2 + 2:
  thm
```

the record update definition uses `K` to throw away the old value of the field, and the `SOME` case is below an abstraction. In the main compset `K` is `set_skip`ped to `SOME 1`, presumably to prevent reduction of the term that will be thrown away, but which means that only weak reduction is applied to the first argument.  Hence the term for the new value of the field is weakly reduced and the `SOME` case is left alone while the `NONE` case is reduced.  I expected the new field value to be strongly reduced, which would reduce both cases.
##

**Comment by mn200** [comment]
Hmm.  Thanks for the report.  I agree that the behaviour is counter-intuitive. Unfortunately, the code in `computeLib` is a black box to us in most respects, so I don't want to claim that we're going to be able to fix it.  I am working on an alternative reduction engine, but I *want* that to only ever do weak reduction, so that is little consolation I guess. 

I'd certainly be willing to take patches against the code.  The various interactions in and around `set_skip` and friends are a definite mess.

**Comment by bacam** [comment]
I've been looking into it and found that it's more complex than I first thought, too.  It seems that sometimes arguments *are* strongly reduced, but I don't know why.  So while I've got a patch that appears to work, I'm going to dig into it a bit more to understand what is happening.  (Also, I'd like to find out why terms get eta-reduced.)

That said, for my original purpose I've just used `set_skip` to get the normal behaviour for `K` back.
