### ISSUE TITLE
add llist_CASES to TypeBase

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#304]
Is there some reason `llist_CASES` isn't in the TypeBase (so things like `Cases_on` would work on lazy lists)?

**Comment by konrad-slind** [comment]
Seems to be an oversight.     --Konrad.

**Comment by xrchz** [comment]
OK, so how do I do that? Can you do it?

**Comment by konrad-slind** [comment]
adjoin_to_theory is what is used. Since lazy lists don't have induction,
you'd
have to add them as a "non-datatype" entry. Here's what it is for bags
(found
at end of bag/bagScript.sml:

val _ = adjoin_to_theory
  {sig_ps = NONE,
   struct_ps = SOME (fn pps =>
    let fun pp_line s = (PP.add_string pps s; PP.add_newline pps)
    in
     app pp_line
     ["val _ = ",
      " TypeBase.write",
      " [TypeBasePure.mk_nondatatype_info",
      "  (alpha --> numSyntax.num,",
      "    {nchotomy = SOME BAG_cases,",
      "     induction = SOME STRONG_FINITE_BAG_INDUCT,",
      "     size = SOME(Parse.Term`\\(obsize:'a->num) (y:'b). bag$bag_size
obsize`,CONJ BAG_SIZE_EMPTY BAG_SIZE_INSERT),",
      "     encode=NONE})];\n"
      ] end)};

You'd have

   SOME llist_CASES for the nchotomy field, and NONE for all the others.

 This would support Cases and Cases_on, but not much else.

It would also be preferable to have the distinctness and 1-1 theorems
added, so that the
simplifier could pick them up. But that would require expanding the fields
in the record used
as input to TypeBasePure.mk_nondatatype_info.

Konrad.
