### ISSUE TITLE
Respect type variables when parsing overloads

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#361]
I'd like to write an overload like this:

    val _ = overload_on("foo", ``bar (:'b)``)

and then when I try to parse a term like this:

    ``baz (x:'a -> 'b) ==> foo``

I would like the foo to desugar to as if I had written ``bar (:'b)`` directly.
The current behaviour is as if I instead wrote ``bar (:'c)``, which is not so nice.

Note that for term variables, the right thing happens:

    val _ = overload_on("foo2", ``bar b``)

then

   ``baz2 (b:'a itself) ==> foo2``

acts as if I had written ``bar b`` (the ``b`` is the same as in the antecedent).

**Comment by mn200** [comment]
As discussed in person, this behaviour is entirely as intended, and needs to stay as is.  Moreover, in the case of `itself`, because there is only one value in the type, overloading to a variable with the desired type, gives the right behaviour, particularly if one rewrites with the theorem that maps every value of `'a itself` to that type's one constant.
