### ISSUE TITLE
uo files do not include dependencies that aren't listed in INCLUDES directories

### ISSUE THREAD

**Issue by xrchz** [HOL-Theorem-Prover/HOL#385]
If a theory depends on a file that is in a directory not in one of the `INCLUDES` (and not in some special base set, probably whatever is built into the `hol` executable) then that file is incorrectly absent from the corresponding `Theory.uo` file.

**Comment by mn200** [comment]
This is working as intended.  The problem is that automatic dependency analysis would otherwise pick up things like `structure Foo = struct ... end ; open Foo` and decide that there was a dependency on `Foo`.  Moreover, assuming it could correctly determine which references were indeed to "remote" structures/files and not to internal ones like the above, what exactly should Holmake do?  Assume that that file should be in the current directory?  If not, which directory?  

I can imagine scenarios where you want a script/theory to depend on something that might be generated through a makefile rule.  If so, you should explicitly document the dependency in the Holmakefile, so that Holmake can go ahead and build it as necessary.
