### ISSUE TITLE
Holyhammer compilation fails on first try

### ISSUE THREAD

**Issue by HeikoBecker** [HOL-Theorem-Prover/HOL#405]
Hello,
when using a clean checkout of HOL4, on my Debian 8 machine, the build process crashes when building Holyhammer for the first time.

    Building directory src/holyhammer/hh/hh1 [09 Mar, 09:46:56]
    lib.{cmi,cmx}                                                                OK
    fusion.{cmi,cmx}                                                             OK
    basics.{cmi,cmx}                                                             OK
    features_dt.cmx   | printer..         \ Holmake: Fail exception: Unknown result status
    
    Build failed in directory /DIR/Git_Repos/HOL/src/holyhammer/hh/hh1 (exited with code 1)

Running `bin/build` again once or twice, HOL4 compiles without any problems.

Sometimes I get the additional error that:

    simp.{cmi,cmx}  : Use (&&) instead.                                          Holmake: Fail exception: Unknown result status
    
    Build failed in directory /DIR/HOL/src/holyhammer/hh/hh1 (exited with code 1)

I am using poly-ml, version 5.6 and configured HOL4 using `poly < tools/smart-configure.sml`

**Comment by barakeel** [comment]
It seems that you have one of the newest version of ocaml. Please give me your version number.
I fixed some of the deprecated symbols but not all because I am afraid it would break backward compatibility.

Could you test if the my most recent commit fixes the problem? For example by running Holmake in
HOL/src/holyhammer/hh/hh1.

If it fails, I would like see to the result of those two commands on the same directory:
  Holmake -j 1 clean 
  Holmake -j 1

Thank you,

**Comment by mn200** [comment]
In addition, the  `Unknown result status` is an error in Poly/ML.  If you use a more recent version (5.6.1, or perhaps the forthcoming 5.7), that should occur much less often.  You should never see it if you do everything with the `-j1` flag as @barakeel suggests (though you then lose the multi-processing).

**Comment by mn200** [comment]
I should have said also that the `-j1` option can be passed to `build` too.

**Comment by HeikoBecker** [comment]
Hello,

@barakeel  my ocaml version is 4.03
I have rerun the compilation with your latest commit and the compilation succeeds now.
Thank you.
