### ISSUE TITLE
Quit on failure should be the default mode for Holmake

### ISSUE THREAD

**Issue by AndreasLoow** [HOL-Theorem-Prover/HOL#576]
Quit on failure mode is currently hidden behind a flag `--qof` for Holmake. I think making quit on failure the default would make sense.

My main reason for thinking this is that one cannot differentiate between a failed build and a successful build of a theory if the theory depends on cheated theorems. If such theory succeeds to build the build log will say CHEATED because of the theory's dependencies. But the log will say CHEATED also when some proof in such theory fail. So one cannot tell just by looking at the build log if the build _actually_ succeeded or not. (Or did I miss something?) In most cases you want to have that information, so quit on failure should be the default I think. I also think making CHEATED by default mean cheated rather than cheated-or-failed would make the tool easier to understand for new users.

Are there any arguments against such change?

**Comment by mn200** [comment]
I agree that by default the CHEATED annotation is not informative enough because there are two scenarios: 
- the user explicitly wrote `cheat` in their proof; or
- the proof failed and the "make it OK" machinery took over and `cheat`-ed it for the user to as to make more progress

The `--qof` annotation prevents the latter from happening at all.  I think the priority should actually be to make the second case distinguishable from the first.  I am less confident about what the default wrt `--qof` should be.

**Comment by AndreasLoow** [comment]
I _think_ the default mode for many other build tools, at least for general purpose languages, is to quit on first failure; so doing the same would potentially make Holmake less confusing for people expecting it to work like other build tools ("PoLA"). But what's reasonable for general purpose languages might not necessarily be reasonable for HOL4...

**Comment by xrchz** [comment]
+1 to `--qof` as default

**Comment by mn200** [comment]
Fair enough.  I think the expert users who want the "keep going" behaviour can learn to use a `--noqof` option.

**Comment by xrchz** [comment]
There is already `--keep-going`. Is that not the same as `--noqof`? (I think it should be...)

**Comment by thtuerk** [comment]
`--keep-going` is different. After an error occurred in one file, it tries other files, that don't depend on it. If it is not given, `Holmake` aborts after the first error encountered.

I usually run Holmake with option `--qof -k`. Compilation aborts for a script-file and everything depending on this script-file, if an error is encountered. However, independent script-files are still run. I find this handy when modifying multiple script-files at the same time. This often happens if I structure larger developments into multiple theories and need to add a simple, auxiliary lemma to one theory in order to prove a theorem in another one.

**Comment by mn200** [comment]
@thtuerk is right; it can be a little confusing keeping this all straight in one's head.

**Comment by thtuerk** [comment]
Perhaps one should also change the Holmakefile option `QUIT_ON_FAILURE` to something like `NO_QUIT_ON_FAILURE`. In `tools/Holmake/Holmake.sml` line 371 onwards I could imagine a change like 

```
val hmake_noqof = member "NO_QUIT_ON_FAILURE" hmake_options
...
val quit_on_failure = quit_on_failure andalso (not hmake_noqof)
```

**Comment by mn200** [comment]
If people want this sort of effect, they should be using the `CLINE_OPTIONS` machinery.  This older `OPTIONS` approach is not the right way to do this anymore.

**Comment by thtuerk** [comment]
I see. Sorry, I was not aware of `CLINE_OPTIONS`.

**Comment by mn200** [comment]
No problem. I just checked, and `OPTIONS` is no longer documented in the Description manual (and `CLINE_OPTIONS` is).  (Though I see that the example usage claims that `--qof` might be a useful value which is unlikely.  I will change this.)

**Comment by AndreasLoow** [comment]
Thanks for the fix/update!
