### ISSUE TITLE
Predictable parts of Syntax files could be generated into Theory files.

### ISSUE THREAD

**Issue by talsewell** [HOL-Theorem-Prover/HOL#608]
From listSyntax.sml:
  val hd_tm = prim_mk_const {Name = "HD" ...
  val tl_tm = ...
etc.

This is quite predictable. It could be generated, and it could be generated into the listTheory file if the export mechanism was extended with a hook that looks something like:

val _ = save_const ("hd_tm", ``HD``);

Of course, listSyntax defines more features than just names for the accessors. But some other Syntax files really don't do very much except provide "safe" identifiers by which ML code (particularly in the associated Lib file) can manipulate terms without using parses/quotes that might evaluate to the wrong thing.

Since it's possible to do quite a lot with just the constants (via strip_comb/same_const and list_mk_icomb) this might make some Syntax files redundant.

**Comment by konrad-slind** [comment]
Anthony Fox wrote some functions that compress a lot of the boilerplate.
See HolKernel.syntax_fns{1-4}. Examples of use are in various places, e.g.,
src/floating-point/fp-functor.sml.

Konrad.

**Comment by mn200** [comment]
I'd rather write `numSyntax.mk_plus(t1,t2)` than `list_mk_comb(plus_tm, [t1,t2])`, particularly if `numSyntax` is open so that the former becomes even shorter.  But yes, the simplest of these functions are just minor conveniences. 

Complicated or not, I don't want their implementations in theory files however.  The decision to make theory files "SML code" has bitten us numerous times: the trend is to move more and more code *out* of theory files.  Instead, for the most complicated cases, there is now machinery to have theory files force the loading of auxiliary SML code files: use `Theory.add_ML_dependency`.

For accessors, constructors, destructors *etc*, use/extend the `TypeBase` API and have the datatype package make the necessary changes to the type base when types are defined. 

If you want arbitrary constants of a given theory, use `prim_mk_const{Thy = "list", Name = "HD"}`.

**Comment by talsewell** [comment]
Hmm, yes. What I continue to learn here is that I still have no idea what the real design constraints of this system are. Thanks for the responses.

**Comment by konrad-slind** [comment]
Well there is a collection of goals. One of them is to make coding up proof
procedures (ad hoc ones, or heavy-weight ones, like decide or metis) as
convenient as possible. The thySyntax modules support that since they
support both basic term construction and, in some case, more elaborate
support.

Konrad.
