### ISSUE TITLE
Hide excessive priming with parse/print level translation

### ISSUE THREAD

**Issue by mn200** [HOL-Theorem-Prover/HOL#613]
Because I will soon remove `Globals.priming` I want to support pretty ways of looking at terms/goals that have been heavily ‘primed’.  I think the way to do this is to have (a flag to allow) something like `x''''` to print as `x'₄`.  For input, both this form and the perhaps easier to type `x'4` should be possible. 

While `x'` would obviously continue as `x'`, even `x''` could become `x'₂`, and `x'''` should definitely become `x'₃`.

Yes, of course, yet another flag could allow for Unicode or pure ASCII renders.

**Comment by mn200** [comment]
Thanks for this!  I didn't know about ACL2's example.  In the interests of space, I don't know that we really need the extra trailing apostrophe, but it's certainly worth considering.

I think you're right that the superscript is better. 

I'm not sure what you mean by *“is the ASCII presentation still the old way?”*  My intent would be to have all three of `x''''`,  `x'⁴`, and  `x'4` map to the same underlying variable (whose name would be `x''''`), and thus to the same printing form of `x'⁴` (modulo choice of flags; *e.g.* the existing `PP.avoid_unicode` would cause `x'4` to be used instead).  This would be a change: currently, all three of those strings would happily map to distinct variables with those exact names.

**Comment by binghe** [comment]
Thanks, now I understand that you're also changing the ASCII variable names.   I personally think that saving one trailing apostrophe doesn't save too much, beside it makes `x'⁴` looks like the power-4 of `x'`.  But if we make that superscript number bounded by something, either two single quotes, or small parenthesizes (e.g. x^{(4)}), no ambiguity any more.

Also, recall in Differentiation Calculus, the single-variable derivatives were denoted by prims, e.g. `x'` means one-order derivative of `x`, i.e. `dx/dt` if `x=x(t)`. Then general n-order derivatives were denoted by `x^{(n)}`. However this is not a good way in ASCII representation, as parenthesis shouldn't be part of a symbol/variable, but if there're small parenthesis symbols in Unicode, maybe it could be a possible alternative Unicode representation.

**Comment by konrad-slind** [comment]
So (going back to the beginning of the thread) is the idea to have only one
way of renaming variables (currently Globals.priming allows more) and also
make reading of highly renamed variables easier?

Konrad.

**Comment by mn200** [comment]
Hmm.  Inevitably, discussions about syntax are the most involved :)  When I get round to this I'll play with all the options...

**Comment by mn200** [comment]
@konrad-slind Yup, exactly.  Globals.priming is an efficiency disaster when you're multi-threaded.

**Comment by myreen** [comment]
(Sorry for spamming, I initially pasted this into the wrong issue.)

In CakeML circles, there has been talk about a desire to have an option which *makes generated names random*. The motivation for this is that randomness would force proof developers to avoid mentioning generated names explicitly in proof tactics. This option will lead to more good use of `rename` tactics.

Consider an example: when one proves something interactively, a variant of variable `x` might become `x'54` but when one reruns the proof the same variable might be called `x'71`. This means that a proof that explicitly mentions `x'54` is highly unlikely to pass a regression test due to the randomness.

@mn200 would such a randomness option be possible in your reworked version of priming variables?

**Comment by mn200** [comment]
Not in such a straightforward way; the point of the exercise is to remove references and switches from the kernel entirely (thereby making it cleaner for concurrent execution, and more efficient generally). 

For the CakeML application, one could try to rebind specific tactics and/or `>>/THEN/\\` to introduce random names as a separate step: this would be a little tricky because one would have to know which names were safe to mess with.  (You could examine the free variables before and after the tactics were applied, and assume that new free variables could be messed with.)

**Comment by xrchz** [comment]
I just want to clarify that this random generated names proposal is neither specific to nor necessary for CakeML.

**Comment by mn200** [comment]
Indeed!

**Comment by myreen** [comment]
@mn200 Do I understand this correctly: (1) the real problem is that I suggested an optional switch; and (2) the problem does not stem from random-name-generation.

However, I realise that many existing scripts would break so badly with random-name-generation enabled that we would not like to make it HOL's default (and once switches are forbidden: only) behaviour.

When I find time, I'll try implementing a wrapper around `THEN` which replaces all new variables with a prime to some random name, e.g. `post'` could become `post_45`.

**Comment by mn200** [comment]
@myreen I think you have it right.  The idea of the post-processing step that messes with primed variables is probably a reasonable one, though some scripts might deliberately choose primes to a certain level.  (I.e., I might want `s` and `s'` as my state variables.)  In that case, the post-processor would have to be smarter (only mess with more heavily primed things, say).
