### ISSUE TITLE
Form to handle printing/parsing of arbitrary variables

### ISSUE THREAD

**Issue by mn200** [HOL-Theorem-Prover/HOL#614]
When a variable has an “interesting” name, there should nonetheless be a way of inputting it.  I think the syntax
```
  $var$(long name with spaces and rparens escaped with backslashes and who knows what else)
```
should do the trick.  (One might insist that newlines be `\n` instead of “raw”.)

This would make our pretty-printer closer to being “Pollack consistent”.

**Comment by myreen** [comment]
In CakeML circles, there has been talk about a desire to have an option which *makes generated names random*. The motivation for this is that randomness would force proof developers to avoid mentioning generated names explicitly in proof tactics. This option will lead to more good use of `rename` tactics.

Consider an example: when one proves something interactively, a variant of variable `x` might become `x'54` but when one reruns the proof the same variable might be called `x'71`. This means that a proof that explicitly mentions `x'54` is highly unlikely to pass a regression test due to the randomness.

@mn200 would such a randomness option be possible in your reworked version of priming variables?
