### ISSUE TITLE
A canonical way to find constant definitions

### ISSUE THREAD

**Issue by IlmariReissumies** [HOL-Theorem-Prover/HOL#627]
Any code that uses the CakeML translator sooner or later seems to evolve to include following ugly copypasta:

```
fun def_of_const tm = let
  val res = dest_thy_const tm handle HOL_ERR _ => failwith ("Unable to translate: " ^ term_to_string tm)
  val name = (#Name res)
  fun def_from_thy thy name =
    DB.fetch thy (name ^ "_def") handle HOL_ERR _ =>
    DB.fetch thy (name ^ "_DEF") handle HOL_ERR _ =>
    DB.fetch thy (name ^ "_thm") handle HOL_ERR _ =>
    DB.fetch thy name
  val def = def_from_thy (#Thy res) name handle HOL_ERR _ =>
            failwith ("Unable to find definition of " ^ name)
  in def end
```

As a nicer alternative, could there be some facility in HOL that given a constant returns “the defining equation”, where I mean the definition that the user intended to be the defining equation.

By default, the defining equation would be theorem returned by `Define`, but in some cases the user might like to override this e.g. after removing `fix_clock` or once a delayed termination proof has been completed (`terminationTheory`).

**Comment by konrad-slind** [comment]
This is a good idea. However, some functions come with a nice abstract
characterization and also an efficient executable form. Which one should be
"the" definition?

**Comment by myreen** [comment]
@konrad-slind I would like the default to be the theorem the user gets back from `Define`. I guess this is the "nice abstract characterization" rather than the "efficient executable form".

I'm guessing that by "efficient executable form" you mean special equations that make compsets go fast, e.g. using pattern matching on `BIT1` and `BIT2` etc. I don't think such special-purpose equations should be the "the definition".

**Comment by konrad-slind** [comment]
They deal with this a lot in ACL2. There they use the "MBE" (Must Be
Executable) construct to pair an "easy-to-reason" about presentation of a
function with a "fast" version, used for execution. In order to use this,
one has to prove the two equivalent. In practice, this is used to combine
recursive presentations of function with their tail-recursive equivalents.

Also, there is an analogue of the TypeBase, called the DefnBase
(src/1/DefnBase.sml). It never really got off the ground, but I could see
something like it being used to organize the universe of definitions. But
that would be an extra thing to add to the system state.

**Comment by mn200** [comment]
Some recent thinking suggests that it might be easiest to have user-facing functions automatically tag all theorems returned to users with an attribute such as `userdef`. TFL would add this to the theorems it returns as top-level characterisation even though these aren't strictly definitions.  

This tag could also be manually applied to theorems at a user's discretion. There could be a `nouserdef` attribute (by analogy with `nocompute`) to stop this happening.  Internal definitions made by tools would never add this tag.

**Comment by mn200** [comment]
Though the induction principle storing part of this has not been extensively exercised, the "user" definition part now has (thanks to work in CakeML), so I think it's fair to say this has been done (as of db75935043b).
