### ISSUE TITLE
Metis catches the Interrupt exception

### ISSUE THREAD

**Issue by barakeel** [HOL-Theorem-Prover/HOL#638]
I would like to interrupt a thread running Metis cleanly. However I am not able to because Metis catches the exception given Thread.interrupt. Therefore, I have to use Thread.kill which I would like to avoid as
recommended in the PolyML compiler documentation.

**Comment by mn200** [comment]
Really?  `Thread.Interrupt` is the same as the normal `Interrupt` that is sent by the REPL when you hit `Control-C`.  And we know that interrupt works fine there: we interrupt out-of-control `metis` invocations all the time...

**Comment by barakeel** [comment]
It seems that Thread.interrupt is not working correctly then (or that i am completely off)
Here are two example functions and their behaviour relative to Thread.interrupt:

fun loop () = loop ();
fun wait100 () = OS.Process.sleep (Time.fromReal 100.0);

val worker = Thread.fork (fn () => loop (),[]);  
Thread.interrupt worker;                         
Thread.isActive worker; (true)                        
Thread.kill worker;                                    
Thread.isActive worker;  (false)

val worker = Thread.fork (fn () => wait100 (),[]); val worker = ?: Thread.thread
Thread.interrupt worker;
Thread.isActive worker; (false)

Why is Metis (inside a thread) behaving like loop and not like wait100 ? (I tried specifying InterruptAsynch but this did not change the results).

Finally, the behaviour seems a bit random, sometimes interrupt does not work for wait100 and works for loop.

**Comment by mn200** [comment]
According to https://www.polyml.org/documentation/Reference/Threads.html none of this code is likely to work because you need to set the `EnableBoradcastInterrupt` flag/attribute in order to have the threads see the interrupt at all.  Moreover, looking at Poly/ML's code for this stuff, `InterruptSynch` is set.  

(The sleeping thread is presumably not active even before you try to interrupt it because it's blocked on the `sleep` system call.)

Perhaps you could try the (coming from Isabelle) code: `Future.interruptible_task` to do this sort of thing...

**Comment by barakeel** [comment]
Until further testing, I got it too work with these options [Thread.InterruptState Thread.InterruptAsynch, Thread.EnableBroadcastInterrupt true]. Only setting Thread.EnableBroadcastInterrupt true was not enough which threw me off. 

Sleep is active before interrupt ... Thanks for the help
