### ISSUE TITLE
What does this author mean?

### ISSUE THREAD

**Issue by Hibou57** [HOL-Theorem-Prover/HOL#684]
On page 145 of https://hol-theorem-prover.org/hol-course.pdf , the author says:

> there are bugs (currently e. g. some trouble with certain mutually
> recursive definitions)

What does the author mean? Is this related to soundness/consistency or to something else?

**Comment by konrad-slind** [comment]
I think he means that the package fails to make some datatype declarations
when it ought to succeed. I doubt there's a soundness/consistency problem
since the package uses only soundness-preserving mechanisms.

**Comment by thtuerk** [comment]
Dear Yannick,

please use the mailing list of questions like this. Issues for the source code are not the place for it.

The part you quote is something I wrote about the datatype package.

Just to avoid misunderstandings. The datatype package is great, I would not want to work without it and it is a very important part of HOL. However, in my opinion one needs to be aware of what it does and that you need to check the results. It is a big, complicated piece of SML code that after a lot of processing ultimately calls low-level kernel functions. There is no strict guarantee that the datatype defined is really what the user wanted. This is not related to soundness or consistency.

The kernel is very carefully designed and checked. Moreover, the kernel is comparably small. In LCF style provers a core idea is that you only have to trust the kernel. Hopefully this kernel ensures soundness and consistency. The code you write on top of the kernel can contain bugs. However, whatever you do, proofs go through the kernel and however buggy your code is it should not be possible to prove a wrong statement. However, there is a catch: If you use complicated code like the datatype package not for proving things but for defining functions and datatypes, you cannot be sure that the datatypes or functions defined by this complicated piece of code are really what the user wanted.

In practice, the datatype package is very reliable and absolutely essential for working with HOL. If you are paranoid, you can always prove a few theorems about the datatype you just defined. Just something to convince yourself that what you defined is really what you had in mind. 2 years ago, when I wrote the slides you refer to, there were a few known bugs in the datatype package in some very rare special cases dealing with mutual recursive datatypes. I can't remember what is was and don't think it is worth the time digging it up. I don't know whether this got fixed by now. Anyhow, since these were unimportant corner-cases, it does not really matter.
I was trying to teach my students about LCF style and possible pitfalls. The comment you asked about has to be read with the same mindset as slide 124, slides 165-167, slides 180ff and other places.

Cheers

Thomas

**Comment by Hibou57** [comment]
Oops, sorry for the annoyance.

I agree with this:

> you can always prove a few theorems about the datatype you just defined. Just something to convince yourself that what you defined is really what you had in mind.
