### ISSUE TITLE
Provide fromSeq and theorems in llistTheory

### ISSUE THREAD

**Issue by myreen** [HOL-Theorem-Prover/HOL#817]
I’m always perplexed as to why `llistTheory` is so unintuitive and lacks many things I would expect. I would have expected the `'a llist` type to be defined as:

    Datatype:
      llist = fromList ('a list) | fromSeq (num -> 'a)
    End

Is there are reason why the current definition is so strange? 

_Would anyone object if I were to rework it so that_ `'a llist` _is defined as above?_ 

I would of course update all theorems and add a bunch of theorems that I think ought to be there. I can't promise that my changes will be completely backwards compatible, e.g. I would like `Cases_on` to do the obvious case split based on the definition above; the current behaviour of `Cases_on` is whether it's a `LNIL` or `LCONS` which is not particularly helpful in proofs about possibly infinite lazy lists.

**Comment by IlmariReissumies** [comment]
The reason the definition is so strange, I think, is that HOL4 doesn't have a proper definitional package for codatatypes. (It would be cool if we did --- we're far behind Isabelle and Coq in that regard). For example, the corresponding datatype in Isabelle is defined as follows (eliding some cruft):

```
codatatype 'a llist= LNil | LCons (lhd:′a) (ltl:′a llist)
```

..which to me is the most natural definition you could possibly have for lazy lists, and one day I hope HOL4 gets a definitional package that would allow us to write this instead. What Michael has tried to do here, I think, is to manually construct something that behaves exactly as the codatatype definition above.

Your proposed definition would perhaps simplify proofs by case split on whether something is finite or infinite, but I disagree that it's not helpful in proofs about possibly empty lists. I don't like that it forces you to care whether your list is finite or infinite: in fact, one of the beauties of codatatypes is that for many purposes you simplify things by not caring. For example, the most common pattern for proving equalities on lazy lists is bisimulation proofs. The first step after using `LLIST_BISIMULATION` to set up the coinduction is typically to case split on whether the outermost constructor is `LNIL` or `LCONS` so that I can unroll one step of the function definition. To case split here on whether something is finite or infinite would not help.

**Comment by mn200** [comment]
The actual fundamental definition is pretty irrelevant.  Clearly, you could define constructors like those on top of the existing base, and show them injective etc.  You could then define the cases theorem you want, and if you were confident that no-one would object, you could register that to be the theorem used by `Cases_on`.  (I'd be cautious: I want to make it easier to do things like ``Cases_on `llist` using myth``; given this facility I don't think the change would be warranted at all.)

Note that your proposed definition makes defining things like append and even cons pretty unpleasant.  In particular, having to futz with indices:
```
  (append (fromList l) l2 = 
      case l2 of
          fromList l' => fromList (l ++ l')
      |  fromSeq s => fromSeq (\n. if n < LENGTH l then EL n l else s (n - LENGTH l))) /\
  (append (fromSeq s) _ = fromSeq s)
```

filter, which might turn a `fromSeq` into a `fromList` would be even more ghastly.

**Comment by mn200** [comment]
Rather than rebuilding it from the ground up: what theorems/constants do you think are missing?

**Comment by ahmedwaqar** [comment]
I have ported some part of stream theory based on llist from Isabelle/HOL afp. Honestly, I struggled alot especially defining the recursive definitions requiring equivalent definition in option theory. Micheal helped alot back then in formalizing some concepts. I wish to port more of them but got stuck as some concepts were really challenging atleast for me. I'd appreciate if an equivalent definition for llist datatype could simplify proofs. Maybe I can spare sometime to resume porting work.

**Comment by binghe** [comment]
Andrei Popescu ever said that their BNF datatype defining package for Isabelle/HOL can be ported to HOL4 in theory (the whole idea doesn't depend on Isabelle's extension to the original HOL). This requires a deep knowledge on Category Theory and Cardinal Theory, so far beyond my capacity...

**Comment by myreen** [comment]
> what theorems/constants do you think are missing?

I'm missing a convenient `fromSeq` and lemmas describing how most of the functions interact with it. 

After discussion with @mn200 and @IlmariReissumies on Slack, I change my position: this issue should be seen as defining `fromSeq` and adding a bunch of lemmas about it to `llistTheory`.

**Comment by mn200** [comment]
I have half of what we need for a codatatype package in my head I think.  The source material is effectively: [*Universal coalgebra: a theory of systems* by Rutten](https://doi.org/10.1016/S0304-3975(00)00056-6).

**Comment by xrchz** [comment]
Obligatory reference to #266
