### ISSUE TITLE
Bug with quiet mode in Emacs

### ISSUE THREAD

**Issue by myreen** [HOL-Theorem-Prover/HOL#992]
I suspect some new version of Emacs is not working correctly with the HOL mode for Emacs, in partiucular the quiet mode seems to be broken. Here's a transcript:

`M-h` starts HOL:
```
---------------------------------------------------------------------
       HOL-4 [Kananaskis 14 (stdknl, built Mon Jan 17 10:10:47 2022)]

       For introductory HOL help, type: help "hol";
       To exit type <Control>-D
---------------------------------------------------------------------
```

User copies in input `open ... Definition foo_def ... End` using `M-h C-r`:
```
> > > > <<HOL message: Created theory "test">>
Saved definition ____ "foo_def"
```
Note that the `foo_def` didn't print. We seem to be in quiet mode.

Let's toggle quite mode with `M-h C-q`:
```
> > *** 'Quiet declaration' now true ***
*** Globals.interactive now false ***
```
That's odd.

Now we copy in a definition of `Definition bar_def: ... End` and get:
```
> > # # # # # # Definition has been stored under "bar_def"
val bar_def = ⊢ ∀n. bar n = n − 5: thm
```

Now we start a goal using `M-h g` but get no output at all:
```

```

So we toggle quiet mode again:
```
> > *** 'Quiet declaration' now false ***
> *** Globals.interactive now true ***
```

And now we try to start the goal again with `M-h g` and see that there are two goals:
```
> # # # val it =
   Proof manager status: 2 proofs.
   2. Incomplete goalstack:
        Initial goal:
        ∀n. bar (foo n) = n
   
   1. Incomplete goalstack:
        Initial goal:
        ∀n. bar (foo n) = n
   : proofs
> val it = (): unit
```

**Comment by mn200** [comment]
I can't reproduce this.  What version of emacs are you using, and can you send/attach a minimal example demonstrating the problem?

**Comment by mn200** [comment]
Note also that it's better style to do something like
```
  open dep1 dep2 ..

  val _ = new_theory "foo"
  Definition def1:
     ..
  End
```
with `open` declarations at the top of the file, even before the `new_theory` call.

**Comment by myreen** [comment]
This is the original file:

**Comment by myreen** [comment]
```open HolKernel Parse boolLib bossLib;

val _ = new_theory "test";

Definition foo_def:
  foo n = n + 5
End

Definition bar_def:
  bar n = n - 5
End

Theorem bar_foo:
  ∀n. bar (foo n) = n
Proof
  simp [foo_def,bar_def]
QED

val _ = export_theory();
```

**Comment by myreen** [comment]
Quentin Corradi pointed out to me that the error is likely to be the use of `M-h C-r` where `M-h M-r` was intended. See:

**Comment by myreen** [comment]
I'm closing this because I no longer think it's a bug. We were just using the incorrect key bindings.

However, the prover does get into a funny state if `M-h C-r` is used...

**Comment by dwRchyngqxs** [comment]
I reproduced the described behaviour, I will try to explain how I understand the interaction to make it clearer:

- `M-h h` starts HOL (maybe the missing `h` is a typo in the original message because `M-h` did nothing for me on its own)
- The first `M-h C-r` sends the selected area in "silent mode" (`M-h M-r` produces the intended output)
- `M-h C-q` toogles quiet mode, effectively swapping the behaviour of `M-h M-r` and `M-h C-r` (because the latter just toogles quiet mode, calls the code of the former an re-toogles quiet-mode)
- The next `M-h C-r` sends the region in quiet-mode, but HOL is already in quiet-mode so it gets out of it just for this definition and goes back into it.
- `M-h g` sends the goal to the goalstack, but HOL is in quiet mode so nothing is printed.

Maybe the real issue lies here: do we really want these interactive commands to not ouput anything in quiet mode?

Then the rest is just getting out of quiet mode, sending a second time the goal to the goalstack, and surprisingly there is two goal in the goalstack because nothing was printed the first time.

**Comment by mn200** [comment]
Thanks for explaining all this.  I assumed that the `M-h C-r` was just a typo in the original description for the correct `M-h M-r`.  I didn't even know about `M-h C-r` and have never used it.   In fact, I propose to remove it for the following reasons:

- its effect can be gained by using `C-u C-u M-h M-r`
- quietness is less needed these days given the automatic way `M-h M-r` makes all `open`-s quiet and because `M-h H` also makes things quiet while it executes the startup and region execution. 
- most (all?) other bindings of the form `M-h C-<X>` are toggles (e.g., `M-h C-t` toggles `show_types`; `M-h C-s` toggles the simplifier trace; `M-h C-u` toggles Unicode, *etc.*, *etc.*)
